# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-18 14:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='tel',
            new_name='tel_id',
        ),
        migrations.RenameField(
            model_name='location',
            old_name='department',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='mail',
            old_name='position',
            new_name='mail',
        ),
        migrations.RenameField(
            model_name='tel',
            old_name='tel_1',
            new_name='tel',
        ),
    ]
