# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_auto_20190719_0755'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Info',
        ),
        migrations.AddField(
            model_name='contacts',
            name='info',
            field=models.TextField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='company_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Company'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='mail_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Mail'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='position_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Position'),
        ),
        migrations.AlterField(
            model_name='contacts',
            name='tel_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.Tel'),
        ),
    ]
