# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-19 06:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_auto_20190719_0852'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacts',
            name='fathers_name',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
