# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-07-19 11:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_auto_20190719_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='tel',
            name='tel_1',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='tel',
            name='tel',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
    ]
