# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2019-12-10 07:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_contacts_is_shief'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contacts',
            old_name='is_shief',
            new_name='is_chief',
        ),
        migrations.AlterField(
            model_name='company',
            name='company',
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='department',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='location',
            field=models.CharField(max_length=55, unique=True),
        ),
        migrations.AlterField(
            model_name='mail',
            name='mail',
            field=models.CharField(max_length=40, unique=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='position',
            field=models.CharField(max_length=75, unique=True),
        ),
    ]
