# Generated by Django 2.2.12 on 2021-06-15 17:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_auto_20200419_0901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='is_shief',
        ),
    ]
