version: '3'

services:
    app:
        build: .
#        image: mjeedx/ticketserver:latest
        volumes:
          - /var/www/ticketserver.ua:/var/www/ticketserver.ua
          - /srv/ticketserver/db:/srv/ticketserver/db
        ports:
          - "80:80"
          - "8000:8000"
        env_file: .env
        environment:
#          DB_HOST: ticketserverdb.cjux829ezany.eu-central-1.rds.amazonaws.com
          -  DB_NAME=ticketserver
#          DB_USER: dbuser
#          DB_PASSWD: "!$Eey0uMan"

#    nginx:
#        build: ./nginx
#        volumes:
#          - /var/www/ticketserver.ua/static:/var/www/ticketserver.ua/static
#        ports:
#          - "80:80"

