version: '3'

services:
    app:
        build: .
        volumes:
          - /var/www/ticketserver.ua/static:/var/www/ticketserver.ua/static
          - /var/www/ticketserver.ua/media:/var/www/ticketserver.ua/media
        ports:
          - "8080:8080"

    nginx:
        build: ./nginx
        volumes:
          - /var/www/ticketserver.ua/static:/var/www/ticketserver.ua/static
        ports:
          - "80:80"

