#!/bin/bash

NAME="tickets"                                    # Name of the application
DJANGODIR=$PWD       # Django project directory
echo $DJANGODIR
#SOCKFILE=/srv/run/gunicorn.sock  # we will communicte using this unix socket
IP=0.0.0.0:8000
USER=www-data                                        # the user to run as
GROUP=www-data                                 # the group to run as
NUM_WORKERS=5                                     # how many worker processes should Gunicorn spawn
DJANGO_SETTINGS_MODULE=tickets.settings             # which settings file should Django use
DJANGO_WSGI_MODULE=tickets.wsgi                     # WSGI module name
LOGDIR=$DJANGODIR/logs/gunicorn.log
echo $LOGDIR

echo "Starting $NAME as `whoami`"

# Activate the virtual environment
#cd $DJANGODIR
#source ../bin/activate
export DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE
export PYTHONPATH=$DJANGODIR:$PYTHONPATH

# Create the run directory if it doesn't exist
RUNDIR=$(dirname $SOCKFILE)
test -d $RUNDIR || mkdir -p $RUNDIR

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec gunicorn ${DJANGO_WSGI_MODULE}:application \
  --name $NAME \
  --workers $NUM_WORKERS \
  --user=$USER --group=$GROUP \
  --bind=$IP \
  --log-level=debug \
  --log-file=$LOGDIR
