# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-18 08:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cartridge',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fill_count', models.IntegerField(default=0)),
                ('last_datetime', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True)),
                ('comment', models.TextField(blank=True, max_length=200)),
                ('deleted', models.BooleanField(default=False)),
                ('cartridge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Cartridge')),
            ],
        ),
        migrations.CreateModel(
            name='Modell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modell', models.CharField(max_length=25, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Num',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num', models.IntegerField(unique=True)),
                ('modell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Modell')),
            ],
        ),
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('place', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Status',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=25)),
            ],
        ),
        migrations.AddField(
            model_name='events',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.Status'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Num'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='place',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Place'),
        ),
        migrations.AddField(
            model_name='cartridge',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Status'),
        ),
    ]
