# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-19 13:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_auto_20170419_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Num'),
        ),
    ]
