# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-04-21 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0003_auto_20170419_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='num',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.Num'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='events',
            name='place',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='carts.Place'),
            preserve_default=False,
        ),
    ]
