# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-17 06:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_remove_events_cartridge'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='cart_date',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='carts.Cartridge'),
            preserve_default=False,
        ),
    ]
