# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-18 05:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_events_cart_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='cart_date',
        ),
    ]
