# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-20 12:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0007_remove_events_cart_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='place',
            field=models.CharField(max_length=40),
        ),
    ]
