# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-21 11:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0008_auto_20170920_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartridge',
            name='num',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carts.Num', unique=True),
        ),
    ]
