# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-03-02 07:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sw_list',
            name='port',
            field=models.CharField(default=1, max_length=7),
            preserve_default=False,
        ),
    ]
