# Generated by Django 2.2.12 on 2020-04-19 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macmap', '0002_sw_list_port'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mac_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('port', models.CharField(max_length=7)),
                ('mac', models.CharField(max_length=17)),
            ],
        ),
        migrations.CreateModel(
            name='Sw_db',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vendor', models.CharField(max_length=25)),
                ('model', models.CharField(max_length=30)),
                ('region', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('ipv4', models.CharField(max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='SW_list',
        ),
        migrations.AddField(
            model_name='mac_list',
            name='sw_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='macmap.Sw_db'),
        ),
    ]
