# Generated by Django 2.2.12 on 2020-04-19 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macmap', '0003_auto_20200419_0901'),
    ]

    operations = [
        migrations.AddField(
            model_name='sw_db',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
