# Generated by Django 2.2.12 on 2020-04-22 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macmap', '0004_sw_db_enable'),
    ]

    operations = [
        migrations.AddField(
            model_name='mac_list',
            name='time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sw_db',
            name='name',
            field=models.CharField(blank=True, max_length=35),
        ),
    ]
