# Generated by Django 2.2.12 on 2020-04-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('macmap', '0005_auto_20200422_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mac_list',
            name='time',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
