# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 05:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Img',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='photos')),
            ],
        ),
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imgId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Img')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Users')),
            ],
        ),
        migrations.RemoveField(
            model_name='ansimage',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='category',
            field=models.CharField(max_length=25),
        ),
        migrations.DeleteModel(
            name='AnsImage',
        ),
        migrations.AddField(
            model_name='img',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Category'),
        ),
        migrations.AddField(
            model_name='img',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Users'),
        ),
    ]
