# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-29 08:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20170929_1008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='photo',
            field=models.ImageField(upload_to='photos'),
        ),
    ]
