# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 12:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('polls', '0005_users_us'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='us',
        ),
        migrations.AddField(
            model_name='users',
            name='usrId',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
