# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-02 12:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20171002_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='ip',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
    ]
