# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-04 11:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_auto_20171002_1551'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='name',
            new_name='title',
        ),
    ]
