# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 07:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20171004_1413'),
    ]

    operations = [
        migrations.RenameField(
            model_name='img',
            old_name='user',
            new_name='userId',
        ),
    ]
