# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-05 08:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_auto_20171005_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='polls.Users'),
        ),
    ]
