# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-09 11:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_auto_20171005_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='photo',
            field=models.ImageField(upload_to='photos/%Y/%m/%d'),
        ),
    ]
