# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 07:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20171010_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
