# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-10-27 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0017_auto_20171027_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='imgId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='polls.Img'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
