# Generated by Django 2.2.12 on 2020-04-19 06:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_img_like'),
    ]

    operations = [
        migrations.AlterField(
            model_name='img',
            name='categoryId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='polls.Category'),
        ),
        migrations.AlterField(
            model_name='img',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='likes',
            name='imgId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='polls.Img'),
        ),
        migrations.AlterField(
            model_name='likes',
            name='userId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
