# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2020-02-12 19:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0002_auto_20191216_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
