# Generated by Django 2.2.12 on 2021-06-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticket', '0003_tickets_confirmed'),
    ]

    operations = [
        migrations.AddField(
            model_name='tickets',
            name='date_confirm',
            field=models.DateTimeField(null=True),
        ),
    ]
